services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: unless-stopped
    container_name: document-creator
    volumes:
      - ./Documents:/usr/src/app/Documents
    networks:
      - nginx_nginx-proxy-manager

networks:
  nginx_nginx-proxy-manager:
    external: true
