services:
  document_creator:
    image: api.registry.viomitra.ru/document_creator:latest
    build:
      context: .
    environment:
      NODE_ENV: production
    container_name: document-creator
    volumes:
      - ./Documents:/usr/src/app/Documents
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.document_creator-http.rule=Host(`documentcreator.viomitra.ru `)
        - traefik.http.routers.document_creator-http.entrypoints=http
        - traefik.http.routers.document_creator-http.middlewares=https-redirect
        - traefik.http.routers.document_creator-https.rule=Host(`documentcreator.viomitra.ru `)
        - traefik.http.routers.document_creator-https.entrypoints=https
        - traefik.http.routers.document_creator-https.tls=true
        - traefik.http.routers.document_creator-https.tls.certresolver=le
        - traefik.http.services.document_creator.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
